/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule
module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module t2hcontrol (
  input op4,
  input op3,
  input op2,
  input op1,
  input op0,
  output eA,
  output eB,
  output eC,
  output eW,
  output sA,
  output sALU3,
  output sALU2,
  output sALU1,
  output sALU0,
  output sB,
  output clrO,
  output negO,
  output sW,
  output \s+ ,
  output sAddr,
  output rd,
  output wr,
  output sDout1,
  output sDout0,
  output sI1,
  output sI0
);
  wire sDout0_temp;
  wire s0;
  wire s1;
  wire sDout1_temp;
  wire s2;
  assign s1 = ~ op4;
  assign s2 = ~ op3;
  assign sDout1_temp = ~ op2;
  assign s0 = ~ op1;
  assign sDout0_temp = ~ op0;
  assign eA = ((sDout0_temp & op1 & op2 & op4) | (sDout0_temp & s0 & op3 & s1) | (op0 & sDout1_temp & op4) | (op0 & s2) | (s0 & op2 & op3) | (s0 & op2 & s1) | (op2 & op3 & s1) | (sDout1_temp & s2 & op4));
  assign eB = ((op0 & s0 & sDout1_temp & s2 & s1) | (sDout0_temp & s0 & op2 & s2 & s1) | (sDout0_temp & s0 & sDout1_temp & s2 & op4) | (sDout0_temp & s0 & op2 & op3 & op4) | (op0 & op1 & op2 & s2) | (op0 & op1 & sDout1_temp & op4) | (op0 & op2 & op3 & s1) | (op0 & op2 & s2 & op4) | (op0 & sDout1_temp & op3 & op4) | (op1 & op2 & op3 & s1) | (op1 & sDout1_temp & op3 & op4));
  assign eC = ((op0 & s0 & sDout1_temp & s2 & s1) | (sDout0_temp & s0 & op2 & s2 & s1) | (op0 & op1 & op2 & s2 & s1) | (sDout0_temp & op1 & sDout1_temp & op3 & op4));
  assign eW = ((op0 & op1 & sDout1_temp & op3 & s1) | (sDout0_temp & op1 & op2 & op3 & op4));
  assign sA = (op0 & op1 & s2 & s1);
  assign sALU3 = ((op0 & s2 & s1) | (sDout0_temp & op3) | (op3 & op4));
  assign sALU2 = ((sDout0_temp & op1 & op2) | (op2 & op4) | (s2 & s1));
  assign sALU1 = ((sDout0_temp & op2 & op3 & s1) | (op0 & s2 & s1) | (op1 & op4));
  assign sALU0 = ((op0 & s2) | (op0 & op4) | (op1 & op3 & op4));
  assign sB = ((op0 & op4) | (s0 & op3) | (op3 & s1));
  assign clrO = (sDout0_temp & op1 & s2 & s1);
  assign \s+  = ((op1 & sDout1_temp) | (s0 & op2 & s2) | (op1 & op3));
  assign sAddr = ((op2 & s1) | s2);
  assign rd = ((op0 & op1 & op2 & op3 & op4) | (op0 & op1 & s2 & s1));
  assign wr = ((sDout0_temp & op1 & op2 & op3 & s1) | (op0 & s0 & op3 & s1));
  assign sI1 = ((sDout0_temp & op1 & op2 & s2 & op4) | (op0 & op1 & op2 & op3 & op4));
  assign sI0 = ((sDout0_temp & s0 & sDout1_temp & s2 & s1) | (op0 & s0 & sDout1_temp & op3 & s1) | (sDout0_temp & op1 & sDout1_temp & op3 & s1) | (op0 & op1 & op2 & op3 & op4));
  assign negO = op2;
  assign sW = sDout0_temp;
  assign sDout1 = sDout1_temp;
  assign sDout0 = sDout0_temp;
endmodule

module Mux_16x1_NBits #(
    parameter Bits = 2
)
(
    input [3:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    input [(Bits - 1):0] in_8,
    input [(Bits - 1):0] in_9,
    input [(Bits - 1):0] in_10,
    input [(Bits - 1):0] in_11,
    input [(Bits - 1):0] in_12,
    input [(Bits - 1):0] in_13,
    input [(Bits - 1):0] in_14,
    input [(Bits - 1):0] in_15,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            4'h0: out = in_0;
            4'h1: out = in_1;
            4'h2: out = in_2;
            4'h3: out = in_3;
            4'h4: out = in_4;
            4'h5: out = in_5;
            4'h6: out = in_6;
            4'h7: out = in_7;
            4'h8: out = in_8;
            4'h9: out = in_9;
            4'ha: out = in_10;
            4'hb: out = in_11;
            4'hc: out = in_12;
            4'hd: out = in_13;
            4'he: out = in_14;
            4'hf: out = in_15;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DIG_Sub #(
    parameter Bits = 2
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits-1):0] s,
    output c_o
);
    wire [Bits:0] temp;

    assign temp = a - b - c_i;
    assign s = temp[(Bits-1):0];
    assign c_o = temp[Bits];
endmodule


module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


// The T2H processor is a one clock Harvard 16 bit implementation of a small subset of the Inmos Transputer
module t2h (
  input reset,
  input clock,
  input [7:0] Inst, // instruction to be executed
  input [15:0] dIn, // data from memory
  output [15:0] I, // program counter
  output [15:0] Addr, // Data memory address
  output wr, // write to memory
  output rd, // indicates a read cycle from memory
  output [15:0] dOut // data output to memory

);
  wire [15:0] I_temp;
  wire [15:0] Addr_temp;
  wire [15:0] s0;
  wire [15:0] s1;
  wire eA;
  wire [15:0] A;
  wire [15:0] s2;
  wire eB;
  wire [15:0] B;
  wire eC;
  wire [15:0] C;
  wire [15:0] s3;
  wire eW;
  wire [15:0] s4;
  wire [11:0] s5;
  wire [11:0] s6;
  wire [1:0] sI;
  wire [15:0] \I+1 ;
  wire [15:0] s7;
  wire [15:0] s8;
  wire [15:0] x;
  wire [3:0] s9;
  wire sB;
  wire [1:0] sDout;
  wire sAddr;
  wire [15:0] s10;
  wire [15:0] s11;
  wire [15:0] s12;
  wire \s+ ;
  wire sW;
  wire [15:0] s13;
  wire clrO;
  wire [11:0] s14;
  wire negO;
  wire [7:0] s15;
  wire [7:0] s16;
  wire [7:0] s17;
  wire sA;
  wire [15:0] s18;
  wire [3:0] sALU;
  wire [15:0] s19;
  wire [15:0] s20;
  wire [15:0] s21;
  wire [15:0] s22;
  wire [15:0] s23;
  wire [15:0] s24;
  wire [15:0] s25;
  wire [15:0] s26;
  wire [15:0] s27;
  wire [15:0] s28;
  wire [15:0] s29;
  wire s30;
  wire s31;
  wire s32;
  wire [15:0] s33;
  wire [3:0] s34;
  wire [3:0] s35;
  wire [3:0] s36;
  wire [3:0] s37;
  wire s38;
  wire [3:0] s39;
  wire [3:0] s40;
  wire s41;
  wire s42;
  wire s43;
  wire s44;
  wire s45;
  wire s46;
  wire [3:0] s47;
  wire [3:0] s48;
  wire [4:0] op;
  wire [3:0] s49;
  wire [3:0] s50;
  wire [3:0] s51;
  wire [3:0] s52;
  wire [3:0] s53;
  wire s54;
  wire s55;
  wire s56;
  wire s57;
  wire s58;
  wire s59;
  wire s60;
  wire s61;
  wire s62;
  wire s63;
  wire s64;
  wire s65;
  wire s66;
  wire s67;
  wire s68;
  assign s9 = Inst[3:0];
  assign s39 = Inst[3:0];
  assign s40 = Inst[7:4];
  assign s41 = s40[0];
  assign s42 = s40[1];
  assign s43 = s40[2];
  assign s44 = s40[3];
  assign s45 = (s41 & s42 & s43 & s44);
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i0 (
    .sel( sI ),
    .in_0( \I+1  ),
    .in_1( s7 ),
    .in_2( A ),
    .in_3( dIn ),
    .out( s8 )
  );
  assign x[3:0] = s9;
  assign x[15:4] = s6;
  assign s14[3:0] = s9;
  assign s14[11:4] = s17;
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i1 (
    .sel( sA ),
    .in_0( dIn ),
    .in_1( s18 ),
    .out( s1 )
  );
  assign s46 = (~ s41 & ~ s42 & ((s49[0] | s49[1] | s49[2] | s49[3]) | (s50[0] | s50[1] | s50[2] | s50[3]) | (s51[0] | s51[1] | s51[2] | s51[3]) | (s52[0] | s52[1] | s52[2] | s52[3])) & s43 & s44);
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i2 (
    .sel( s45 ),
    .in_0( s47 ),
    .in_1( s39 ),
    .out( s48 )
  );
  assign op[3:0] = s48;
  assign op[4] = s45;
  assign s47 = (s40 | s53);
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i3 (
    .sel( reset ),
    .in_0( s8 ),
    .in_1( 16'b0 ),
    .out( s0 )
  );
  // I
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i4 (
    .D( s0 ),
    .C( clock ),
    .en( 1'b1 ),
    .Q( I_temp )
  );
  assign s12[0] = 1'b0;
  assign s12[15:1] = x[14:0];
  assign s53[0] = s46;
  assign s53[1] = s46;
  assign s53[2] = s46;
  assign s53[3] = s46;
  assign s58 = op[0];
  assign s57 = op[1];
  assign s56 = op[2];
  assign s55 = op[3];
  assign s54 = op[4];
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i5 (
    .a( I_temp ),
    .b( 16'b0 ),
    .c_i( 1'b1 ),
    .s( \I+1  )
  );
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i6 (
    .a( I_temp ),
    .b( x ),
    .c_i( 1'b1 ),
    .s( s7 )
  );
  t2hcontrol t2hcontrol_i7 (
    .op4( s54 ),
    .op3( s55 ),
    .op2( s56 ),
    .op1( s57 ),
    .op0( s58 ),
    .eA( eA ),
    .eB( eB ),
    .eC( eC ),
    .eW( eW ),
    .sA( sA ),
    .sALU3( s59 ),
    .sALU2( s60 ),
    .sALU1( s61 ),
    .sALU0( s62 ),
    .sB( sB ),
    .clrO( clrO ),
    .negO( negO ),
    .sW( sW ),
    .\s+ ( \s+  ),
    .sAddr( sAddr ),
    .rd( rd ),
    .wr( wr ),
    .sDout1( s63 ),
    .sDout0( s64 ),
    .sI1( s65 ),
    .sI0( s66 )
  );
  // A
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i8 (
    .D( s1 ),
    .C( clock ),
    .en( eA ),
    .Q( A )
  );
  Mux_2x1_NBits #(
    .Bits(12)
  )
  Mux_2x1_NBits_i9 (
    .sel( clrO ),
    .in_0( 12'b0 ),
    .in_1( s14 ),
    .out( s5 )
  );
  assign sALU[0] = s62;
  assign sALU[1] = s61;
  assign sALU[2] = s60;
  assign sALU[3] = s59;
  assign sDout[0] = s64;
  assign sDout[1] = s63;
  assign sI[0] = s66;
  assign sI[1] = s65;
  // O
  DIG_Register_BUS #(
    .Bits(12)
  )
  DIG_Register_BUS_i10 (
    .D( s5 ),
    .C( clock ),
    .en( 1'b1 ),
    .Q( s6 )
  );
  assign s19[0] = 1'b0;
  assign s19[15:1] = A[14:0];
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i11 (
    .a( A ),
    .b( x ),
    .c_i( 1'b0 ),
    .s( s24 )
  );
  assign s29[7:0] = A[15:8];
  assign s29[15:8] = A[7:0];
  assign s33 = (A ^ x);
  assign s30 = A[15];
  assign s31 = A[15];
  assign s49 = A[3:0];
  assign s50 = A[7:4];
  assign s51 = A[11:8];
  assign s52 = A[15:12];
  assign s20[13:0] = A[14:1];
  assign s20[14] = s30;
  assign s20[15] = s30;
  assign s34 = s33[3:0];
  assign s35 = s33[7:4];
  assign s36 = s33[11:8];
  assign s37 = s33[15:12];
  assign s15 = s6[7:0];
  assign s16 = ~ s15;
  assign s38 = ~ ((s34[0] | s34[1] | s34[2] | s34[3]) | (s35[0] | s35[1] | s35[2] | s35[3]) | (s36[0] | s36[1] | s36[2] | s36[3]) | (s37[0] | s37[1] | s37[2] | s37[3]));
  Mux_2x1_NBits #(
    .Bits(8)
  )
  Mux_2x1_NBits_i12 (
    .sel( negO ),
    .in_0( s15 ),
    .in_1( s16 ),
    .out( s17 )
  );
  assign s26[0] = s38;
  assign s26[15:1] = 15'b0;
  // B
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i13 (
    .D( s2 ),
    .C( clock ),
    .en( eB ),
    .Q( B )
  );
  // C
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i14 (
    .D( B ),
    .C( clock ),
    .en( eC ),
    .Q( C )
  );
  // W
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i15 (
    .D( s3 ),
    .C( clock ),
    .en( eW ),
    .Q( s4 )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i16 (
    .sel( sB ),
    .in_0( A ),
    .in_1( C ),
    .out( s2 )
  );
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i17 (
    .sel( sDout ),
    .in_0( A ),
    .in_1( B ),
    .in_2( \I+1  ),
    .in_3( \I+1  ),
    .out( dOut )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i18 (
    .sel( sAddr ),
    .in_0( s4 ),
    .in_1( s10 ),
    .out( Addr_temp )
  );
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i19 (
    .a( s11 ),
    .b( s12 ),
    .c_i( 1'b0 ),
    .s( s10 )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i20 (
    .sel( \s+  ),
    .in_0( s4 ),
    .in_1( A ),
    .out( s11 )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i21 (
    .sel( sW ),
    .in_0( s13 ),
    .in_1( A ),
    .out( s3 )
  );
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i22 (
    .a( x ),
    .b( s4 ),
    .c_i( 1'b0 ),
    .s( s13 )
  );
  Mux_16x1_NBits #(
    .Bits(16)
  )
  Mux_16x1_NBits_i23 (
    .sel( sALU ),
    .in_0( B ),
    .in_1( s19 ),
    .in_2( s20 ),
    .in_3( s21 ),
    .in_4( x ),
    .in_5( s22 ),
    .in_6( \I+1  ),
    .in_7( s23 ),
    .in_8( s24 ),
    .in_9( s25 ),
    .in_10( s26 ),
    .in_11( s27 ),
    .in_12( s28 ),
    .in_13( s29 ),
    .in_14( C ),
    .in_15( Addr_temp ),
    .out( s18 )
  );
  assign s21 = (A ^ B);
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i24 (
    .a( A ),
    .b( B ),
    .c_i( 1'b0 ),
    .s( s22 )
  );
  assign s23 = (A & B);
  DIG_Sub #(
    .Bits(16)
  )
  DIG_Sub_i25 (
    .a( B ),
    .b( A ),
    .c_i( 1'b0 ),
    .s( s28 )
  );
  assign s32 = (s31 ^ B[15]);
  assign s27 = (A | B);
  Mux_2x1 Mux_2x1_i26 (
    .sel( s32 ),
    .in_0( s67 ),
    .in_1( s31 ),
    .out( s68 )
  );
  assign s67 = (~ s28[15] & ~ s38);
  assign s25[0] = s68;
  assign s25[15:1] = 15'b0;
  assign I = I_temp;
  assign Addr = Addr_temp;
endmodule
